coverage:
  status:
    project:
      default:
        target: 80%
        # This is the allowed decrease in coverage before we
        # throw an error.
        threshold: 10%
    patch:
      default:
        target: 0%
        # This is the allowed decrease in coverage before we
        # throw an error.
        threshold: 10%
