//! Regression tests for `Database::save` output being accepted by
//! KeePassXC 2.7+. Two writer bugs were diagnosed against the
//! `tests/resources/test_db_kdbx41_features.kdbx` fixture (a real KDBX
//! 4.1 file generated by KeePassXC 2.7.12):
//!
//!   1. Nullable booleans (`EnableSearching`, `EnableAutoType`) must
//!      serialize the unset state as the literal string "null", not as
//!      an empty self-closing element. KeePassXC rejects empty
//!      elements with `Invalid <field> value`.
//!
//!   2. `AutoType::DataTransferObfuscation` must serialize as the
//!      integer `0`/`1`, not the boolean string `True`/`False`.
//!      KeePassXC rejects bool strings with `Invalid number value`.
//!
//! These tests assert on the literal XML bytes our writer produces;
//! a parser-level self-roundtrip would not catch either bug because
//! our deserializer is permissive enough to accept both the broken
//! and the correct forms.

#![cfg(feature = "save_kdbx4")]

use keepass::{Database, DatabaseKey};

const FIXTURE_PATH: &str = "tests/resources/test_db_kdbx41_features.kdbx";
const FIXTURE_PASSWORD: &str = "correct horse battery staple";

fn load_and_resave_xml() -> String {
    let mut f = std::fs::File::open(FIXTURE_PATH).expect("open fixture");
    let db = Database::open(&mut f, DatabaseKey::new().with_password(FIXTURE_PASSWORD)).expect("parse fixture");

    let mut buf = Vec::new();
    db.save(&mut buf, DatabaseKey::new().with_password(FIXTURE_PASSWORD))
        .expect("save fixture");

    let xml = Database::get_xml(
        &mut std::io::Cursor::new(&buf),
        DatabaseKey::new().with_password(FIXTURE_PASSWORD),
    )
    .expect("decrypt re-save");
    String::from_utf8(xml).expect("xml is utf-8")
}

#[test]
fn enable_searching_unset_serializes_as_literal_null() {
    let xml = load_and_resave_xml();
    assert!(
        xml.contains("<EnableSearching>null</EnableSearching>"),
        "expected '<EnableSearching>null</EnableSearching>'; KeePassXC \
         requires the literal \"null\" string for None and rejects empty \
         self-closing elements with \"Invalid EnableSearching value\". \
         Got XML:\n{}",
        xml,
    );
}

#[test]
fn enable_auto_type_unset_serializes_as_literal_null() {
    let xml = load_and_resave_xml();
    assert!(
        xml.contains("<EnableAutoType>null</EnableAutoType>"),
        "expected '<EnableAutoType>null</EnableAutoType>'; same root \
         cause as `enable_searching_unset_serializes_as_literal_null`. \
         Got XML:\n{}",
        xml,
    );
}

#[test]
fn data_transfer_obfuscation_serializes_as_integer_not_bool_string() {
    let xml = load_and_resave_xml();
    assert!(
        xml.contains("<DataTransferObfuscation>0</DataTransferObfuscation>"),
        "expected '<DataTransferObfuscation>0</DataTransferObfuscation>'; \
         the KDBX schema records this field as an integer (0/1) and \
         KeePassXC rejects bool strings with \"Invalid number value\". \
         Got XML:\n{}",
        xml,
    );
    assert!(
        !xml.contains("<DataTransferObfuscation>False</DataTransferObfuscation>"),
        "DataTransferObfuscation must not be serialized as the bool \
         string \"False\". Got XML:\n{}",
        xml,
    );
    assert!(
        !xml.contains("<DataTransferObfuscation>True</DataTransferObfuscation>"),
        "DataTransferObfuscation must not be serialized as the bool \
         string \"True\". Got XML:\n{}",
        xml,
    );
}
