use challenge_response::{
    config::{Config, Mode, Slot},
    error::ChallengeResponseError,
    ChallengeResponse,
};

use thiserror::Error;
use zeroize::{Zeroize, ZeroizeOnDrop};

use crate::key::KeyElement;

pub fn parse_yubikey_slot(slot_number: &str) -> Result<Slot, ParseYubikeySlotError> {
    Slot::from_str(slot_number).ok_or_else(|| ParseYubikeySlotError(slot_number.to_string()))
}

#[derive(Error, Debug)]
#[error("Invalid slot number: '{0}'")]
pub struct ParseYubikeySlotError(pub String);

/// A challenge-response key for challenge-response authentication.
#[derive(Debug, Clone, PartialEq, Zeroize, ZeroizeOnDrop)]
pub enum ChallengeResponseKey {
    /// A local challenge-response key, where the secret is provided by the user at runtime
    LocalChallenge(String),

    /// A YubiKey challenge-response key, where the response is generated by a YubiKey device
    YubikeyChallenge(Yubikey, String),
}

#[derive(Debug, Clone, PartialEq, Zeroize, ZeroizeOnDrop)]
pub struct Yubikey {
    pub serial_number: u32,
    pub name: Option<String>,
}

impl ChallengeResponseKey {
    /// Perform a challenge-response operation using the key, returning the response as a byte vector
    pub fn perform_challenge(&self, challenge: &[u8]) -> Result<KeyElement, KeyChallengeError> {
        match self {
            ChallengeResponseKey::LocalChallenge(secret) => {
                let secret_bytes = hex::decode(secret)?;
                let response = crate::crypt::calculate_hmac_sha1(&[challenge], &secret_bytes)?.to_vec();
                Ok(response)
            }

            ChallengeResponseKey::YubikeyChallenge(yubikey, slot_number) => {
                let mut challenge_response_client =
                    ChallengeResponse::new().map_err(KeyChallengeError::CannotListKeys)?;

                let slot = parse_yubikey_slot(slot_number)?;

                let yubikey_device = challenge_response_client
                    .find_device_from_serial(yubikey.serial_number)
                    .map_err(|e| KeyChallengeError::KeyNotFound {
                        inner_error: e,
                        serial_number: yubikey.serial_number,
                    })?;

                let mut config = Config::new_from(yubikey_device);
                config = config.set_variable_size(true);
                config = config.set_mode(Mode::Sha1);
                config = config.set_slot(slot);

                let hmac = challenge_response_client
                    .challenge_response_hmac(challenge, config)
                    .map_err(KeyChallengeError::KeyChallenge)?;

                Ok(hmac.to_vec())
            }
        }
    }

    /// Get a list of all available YubiKey devices that can be used for challenge-response authentication
    pub fn get_available_yubikeys() -> Result<Vec<Yubikey>, ChallengeResponseError> {
        let mut challenge_response_client = ChallengeResponse::new()?;
        let mut response: Vec<Yubikey> = vec![];

        let yubikeys = challenge_response_client.find_all_devices()?;
        for yubikey in yubikeys {
            let serial_number = match yubikey.serial {
                Some(n) => n,
                None => continue,
            };

            response.push(Yubikey {
                serial_number,
                name: yubikey.name,
            });
        }
        Ok(response)
    }

    /// Get a YubiKey device matching the provided serial number, or if no serial number is
    /// provided, get the single available YubiKey device.
    ///
    /// Returns an error if no devices are available, if multiple devices are available but
    /// no serial number is provided, or if a serial number is provided but no matching device
    /// is found.
    pub fn get_yubikey(serial_number: Option<u32>) -> Result<Yubikey, GetKeyError> {
        let all_yubikeys =
            ChallengeResponseKey::get_available_yubikeys().map_err(GetKeyError::CannotListKeys)?;

        if all_yubikeys.is_empty() {
            return Err(GetKeyError::NoKeys);
        }

        if let Some(n) = serial_number {
            all_yubikeys
                .into_iter()
                .find(|k| k.serial_number == n)
                .ok_or(GetKeyError::KeyNotFound { serial_number: n })
        } else if all_yubikeys.len() == 1 {
            #[allow(clippy::indexing_slicing)] // we have already checked that there is exactly 1 yubikey
            Ok(all_yubikeys[0].clone())
        } else {
            Err(GetKeyError::AmbiguousKey)
        }
    }
}

/// Errors that can occur during the challenge-response operation for a challenge-response key
#[derive(Error, Debug)]
pub enum KeyChallengeError {
    /// Errors related to the local challenge-response key secret, e.g. if the secret is not valid
    /// hex data or if it is valid hex data but has an incorrect length
    #[error("Invalid local challenge key secret")]
    InvalidLocalSecret(#[from] hex::FromHexError),

    /// Errors related to the local challenge-response key secret having an incorrect length, e.g.
    /// if the secret is valid hex data but does not have the correct number of bytes for a
    /// challenge-response key (e.g. 16 bytes for a 128-bit key)
    #[error("Local challenge key secret is valid hex data, but incorrect length")]
    InvalidLocalSecretLength(#[from] cipher::InvalidLength),

    /// Cannot list available YubiKey devices, e.g. if there is an I/O error communicating with the
    /// system or if the underlying library returns an error
    #[error("Cannot list challenge-response keys: {0}")]
    CannotListKeys(ChallengeResponseError),

    /// Cannot parse the YubiKey slot number, e.g. if the slot number is not a valid integer or if
    /// it is not a valid slot number for a YubiKey device
    #[error(transparent)]
    KeySlot(#[from] ParseYubikeySlotError),

    /// Cannot find a YubiKey device matching the provided serial number
    #[error("Cannot find key with serial number {serial_number} - {inner_error}")]
    KeyNotFound {
        serial_number: u32,
        inner_error: ChallengeResponseError,
    },

    /// Cannot perform the challenge-response operation
    #[error("Cannot perform challenge: {0}")]
    KeyChallenge(ChallengeResponseError),
}

/// Errors that can occur when getting a YubiKey device for challenge-response authentication
#[derive(Error, Debug)]
pub enum GetKeyError {
    /// Cannot list available YubiKey devices, e.g. if there is an I/O error communicating with the
    /// system or if the underlying library returns an error
    #[error("Cannot list challenge-response keys: {0}")]
    CannotListKeys(ChallengeResponseError),

    /// No YubiKey devices are connected to the system
    #[error("No keys connected to the system")]
    NoKeys,

    /// Multiple YubiKey devices are connected to the system but no serial number is provided to
    /// disambiguate them
    #[error("Multiple keys are connected - need to provide a serial number")]
    AmbiguousKey,

    /// Cannot find a YubiKey device matching the provided serial number
    #[error("Cannot find key with serial number {serial_number}")]
    KeyNotFound { serial_number: u32 },
}
